version: '3'

services:
  #service redis
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
  #redis-comamnde
  redis-comandedr:
    container_name: redis-comander
    hostname: redis-comander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"